apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listory.fullname" . }}-external-db
  labels:
    {{- include "listory.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalDatabase.password }}
  postgres-password: {{ .Values.externalDatabase.password | b64enc | quote }}
  {{- end }}
