apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listory.fullname" . }}
  labels:
    {{- include "listory.labels" . | nindent 4 }}
type: Opaque
data:
  spotify-client-secret: {{ .Values.spotify.clientSecret | b64enc | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}
