apiVersion: v1
kind: Secret
metadata:
  name: {{ include "listory.fullname" . }}
  labels:
    {{- include "listory.labels" . | nindent 4 }}
type: Opaque
data:
  spotify-client-secret: {{ .Values.spotify.clientSecret | b64enc | quote }}
  jwt-secret: {{ .Values.auth.jwtSecret | b64enc | quote }}

  {{- if .Values.prometheus.basicAuth.enabled }}
  prometheus-basic-auth-username: {{ .Values.prometheus.basicAuth.username | b64enc | quote }}
  prometheus-basic-auth-password: {{ .Values.prometheus.basicAuth.password | b64enc | quote }}
  {{- end }}