name: Helm repo index
on: release
jobs:
  publish:
    name: Publish helm repo index to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Generate index.yaml
        uses: docker://quay.io/helmpack/chart-releaser:v1.0.0-beta.1
        run: |
          mkdir .helm-index
          cr index \
            --charts-repo https://apricote.github.io/Listory
            --package-path charts
            --owner owner
            --git-repo Listory
            --index-path .helm-index/index.yaml

      - name: Publish to gh-pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: .helm-index # The folder the action should deploy.
